version: '3.3'

services:

  agent:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://${JENKINS_IP:-master}:8080/ -labels 'docker' -executors 4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
    secrets:
      - jenkins-user
      - jenkins-token
    networks:
      - jenkins
    deploy:
      placement:
        constraints: 
          - node.role == manager
      resources:
        reservations:
          memory: 256M
        limits:
          memory: 512M

networks:

  jenkins:
    external: true

secrets:

  jenkins-user:
    external: true
    
  jenkins-pass:
    external: true
