version: '3.3'

services:

  prod:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${GITHUB_USER_SECRET:-github-user}
      - PASSWORD_SECRET=/run/secrets/${GITHUB_TOKEN_SECRET:-github-token}
      - COMMAND_OPTIONS=-master http://${JENKINS_IP:-master}:8080/ -labels 'prod' -executors 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - github-user
      - github-token
    networks:
      - jenkins
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          memory: 1G
        limits:
          memory: 2G

networks:

  jenkins:
    external: true

secrets:

  github-user:
    external: true
    
  github-token:
    external: true
