version: '3.2'

services:

  agent:
    image: vfarcic/jenkins-swarm-agent
    privileged: true
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-github-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-github-token}
      - COMMAND_OPTIONS=-master http://${JENKINS_IP:-master}:8080/ -labels 'docker' -executors 4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace:/workspace
    secrets:
      - github-user
      - github-token
    networks:
      - jenkins
    deploy:
      placement:
        constraints: 
          - node.role == manager
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M

networks:

  jenkins:
    external: true

volumes:

  workspace:
    driver: cloudstor:aws
    external: false

secrets:

  github-user:
    external: true
    
  github-token:
    external: true
