version: '3.3'

services:

  master:
    image: vfarcic/jenkins:${JENKINS_TAG:-18.01.18-40}
    ports:
      - 50000:50000
    networks:
      - proxy
      - jenkins
    volumes:
      - jenkins:/var/jenkins_home
    environment:
      - JAVA_OPTS="-Xmx4g"
      - LOGSPOUT=ignore
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=${JENKINS_DOMAIN:-locahost}
        - com.df.port=8080
        - com.df.letsencrypt.host=${JENKINS_DOMAIN}
        - com.df.letsencrypt.email=${LETS_ENCRYPT_EMAIL}
      placement:
        constraints: 
          - node.role == worker
      resources:
        reservations:
          memory: 7G
        limits:
          memory: 7G
    extra_hosts:
      - "${SLACK_SUBDOMAIN}.slack.com:${SLACK_IP}"
    secrets:
      - jenkins-user
      - jenkins-pass

volumes:

  jenkins:
    driver: cloudstor:aws
    external: false

networks:

  proxy:
    external: true

  jenkins:
    external: true

secrets:

  jenkins-user:
    external: true
    
  jenkins-pass:
    external: true
